# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 394e7728a22b4384d23257f4ae7c865e60cb85bdbadbaeac6899df72d1fd68025710668254974e5c7435ef164baaae0b7ea6103c2ee44f993c1378aa5343492c

test:
  secret_key_base: 5441af1b8b9a3a69b163867c356fad9ad42be1dfb9b6278d78c703502e80cb66672d39ed7dde49b1a5f350acc247caf4828899f736e4d583430f3ba3026a6fbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
